#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# setup.sh — Full setup and deployment for SimpleConnect
#
# This script handles everything from scratch:
#   1. Registers (or updates) an Entra ID app for authentication
#   2. Gets the signed-in user's Object ID for admin access
#   3. Creates the Azure resource group
#   4. Deploys the ARM template (ACS, Storage, Key Vault, Functions, App Insights)
#   5. Builds the JS interop bundle and Blazor client
#   6. Publishes and deploys the Functions app
#   7. Updates the Entra app redirect URIs with the deployed URL
#   8. Persists all settings to .env.{environment} for future runs
#
# Prerequisites:
#   - Azure CLI (az) installed and logged in (az login)
#   - .NET 8 SDK, Node.js 18+, jq, zip
#
# Usage:
#   ./setup.sh --env staging --resource-group rg-simcon-staging --location southeastasia
#   ./setup.sh --env prod --resource-group rg-simcon-prod
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------- defaults --------------------------------------------------------
ENVIRONMENT=""
RESOURCE_GROUP=""
LOCATION="southeastasia"
APP_NAME="SimpleConnect"
PROJECT_NAME="simcon"
INFRA_ONLY=false

# ---------- parse arguments --------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)            ENVIRONMENT="$2"; shift 2 ;;
    --resource-group) RESOURCE_GROUP="$2"; shift 2 ;;
    --location)       LOCATION="$2"; LOCATION_SET=1; shift 2 ;;
    --project-name)   PROJECT_NAME="$2"; shift 2 ;;
    --infra-only)     INFRA_ONLY=true; shift ;;
    --help)
      echo "Usage: $0 --env staging|prod --resource-group <rg-name> [--location <region>] [--project-name <name>] [--infra-only]"
      exit 0 ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2; exit 1 ;;
  esac
done

# ---------- interactive prompts for missing values ----------------------------
if [[ -z "$ENVIRONMENT" ]]; then
  read -rp "Environment (staging/prod): " ENVIRONMENT
  if [[ "$ENVIRONMENT" != "staging" && "$ENVIRONMENT" != "prod" ]]; then
    echo "ERROR: Must be 'staging' or 'prod'" >&2; exit 1
  fi
fi

TEMPLATE_FILE="$SCRIPT_DIR/azuredeploy.json"
PARAMETERS_FILE="$SCRIPT_DIR/parameters.${ENVIRONMENT}.json"
ENV_FILE="$SCRIPT_DIR/.env.${ENVIRONMENT}"

# Load persisted values early to use as defaults for prompts
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

if [[ -z "$RESOURCE_GROUP" ]]; then
  default="${RESOURCE_GROUP:-rg-simcon-$ENVIRONMENT}"
  read -rp "Resource group name [$default]: " input
  RESOURCE_GROUP="${input:-$default}"
fi

if [[ "$LOCATION" == "southeastasia" && -z "${LOCATION_SET:-}" ]]; then
  default="${LOCATION:-southeastasia}"
  echo ""
  echo "  Available regions (common):"
  echo "    southeastasia  - Singapore"
  echo "    eastasia       - Hong Kong"
  echo "    japaneast      - Tokyo"
  echo "    koreacentral   - Seoul"
  echo "    northeurope    - Ireland"
  echo "    westeurope     - Netherlands"
  echo ""
  read -rp "Azure region [$default]: " input
  LOCATION="${input:-$default}"
fi

if [[ "$PROJECT_NAME" == "simcon" ]]; then
  if [[ -f "$ENV_FILE" ]] && grep -q 'PROJECT_NAME=' "$ENV_FILE"; then
    # Persisted as "simcon" from a previous run — keep it as default
    default="simcon"
  else
    # First run — generate a random suffix so Azure names don't collide
    RANDOM_SUFFIX=$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 4)
    default="simcon-$RANDOM_SUFFIX"
  fi
  echo ""
  echo "  Project name is used for Azure resource naming (must be globally unique)."
  read -rp "Project name prefix [$default]: " input
  PROJECT_NAME="${input:-$default}"
fi

if [[ ! -f "$TEMPLATE_FILE" ]]; then
  echo "ERROR: ARM template not found at $TEMPLATE_FILE" >&2
  exit 1
fi

# ---------- load persisted settings ------------------------------------------
ENTRA_CLIENT_ID=""
ADMIN_OBJECT_ID=""
FUNCTION_APP_NAME=""
FUNCTION_APP_URL=""
KEY_VAULT_NAME=""

if [[ -f "$ENV_FILE" ]]; then
  echo ">>> Loading persisted settings from $ENV_FILE"
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  echo "  ENTRA_CLIENT_ID  = ${ENTRA_CLIENT_ID:-<not set>}"
  echo "  ADMIN_OBJECT_IDS = ${ADMIN_OBJECT_IDS:-<not set>}"
  ADMIN_OBJECT_ID="${ADMIN_OBJECT_IDS:-}"
fi

save_env() {
  cat > "$ENV_FILE" << EOF
# SimpleConnect persisted settings ($ENVIRONMENT)
# Auto-generated by setup.sh — do not commit to source control
ENTRA_CLIENT_ID="$ENTRA_CLIENT_ID"
ADMIN_OBJECT_IDS="$ADMIN_OBJECT_ID"
RESOURCE_GROUP="$RESOURCE_GROUP"
LOCATION="$LOCATION"
PROJECT_NAME="$PROJECT_NAME"
FUNCTION_APP_NAME="$FUNCTION_APP_NAME"
FUNCTION_APP_URL="$FUNCTION_APP_URL"
KEY_VAULT_NAME="$KEY_VAULT_NAME"
EOF
  echo "  Saved to $ENV_FILE"
}

echo "============================================================"
echo " SimpleConnect — Full Setup ($ENVIRONMENT)"
echo "============================================================"
echo " Resource Group : $RESOURCE_GROUP"
echo " Location       : $LOCATION"
echo " Project Name   : $PROJECT_NAME"
echo "============================================================"

# ---------- 1. Check Azure CLI login ----------------------------------------
echo ""
echo ">>> Checking Azure CLI login..."
if ! az account show --output none 2>/dev/null; then
  echo "ERROR: Not logged in to Azure CLI. Run 'az login' first." >&2
  exit 1
fi

SUBSCRIPTION_NAME=$(az account show --query "name" -o tsv)
echo "  Subscription: $SUBSCRIPTION_NAME"

# ---------- 2. Get signed-in user's Object ID -------------------------------
if [[ -z "$ADMIN_OBJECT_ID" ]]; then
  echo ""
  echo ">>> Getting your user Object ID..."
  ADMIN_OBJECT_ID=$(az ad signed-in-user show --query "id" -o tsv 2>/dev/null || true)

  if [[ -z "$ADMIN_OBJECT_ID" ]]; then
    echo "  Could not auto-detect Object ID (personal accounts may not support this)."
    read -rp "  Enter your Entra Object ID manually: " ADMIN_OBJECT_ID
    if [[ -z "$ADMIN_OBJECT_ID" ]]; then
      echo "ERROR: Admin Object ID is required." >&2
      exit 1
    fi
  fi
else
  echo ""
  echo ">>> Using persisted Admin Object ID: $ADMIN_OBJECT_ID"
fi
echo "  Admin Object ID: $ADMIN_OBJECT_ID"

# ---------- 3. Register or update Entra ID app ------------------------------
echo ""
echo ">>> Registering Entra ID application..."

ENTRA_APP_DISPLAY_NAME="${APP_NAME}-${ENVIRONMENT}"
LOCALHOST_REDIRECT="http://localhost:7071/authentication/login-callback"

if [[ -n "$ENTRA_CLIENT_ID" ]]; then
  echo "  Using persisted app registration: $ENTRA_CLIENT_ID"
else
  EXISTING_APP_ID=$(az ad app list \
    --display-name "$ENTRA_APP_DISPLAY_NAME" \
    --query "[0].appId" -o tsv 2>/dev/null || true)

  if [[ -n "$EXISTING_APP_ID" && "$EXISTING_APP_ID" != "None" ]]; then
    echo "  App registration found: $EXISTING_APP_ID"
    ENTRA_CLIENT_ID="$EXISTING_APP_ID"
  else
    echo "  Creating new app registration: $ENTRA_APP_DISPLAY_NAME"

    ENTRA_CLIENT_ID=$(az ad app create \
      --display-name "$ENTRA_APP_DISPLAY_NAME" \
      --sign-in-audience "AzureADandPersonalMicrosoftAccount" \
      --enable-id-token-issuance true \
      --web-redirect-uris "$LOCALHOST_REDIRECT" \
      --query "appId" -o tsv)

    echo "  Created app: $ENTRA_CLIENT_ID"

    APP_OBJECT_ID=$(az ad app show --id "$ENTRA_CLIENT_ID" --query "id" -o tsv)
    az rest --method PATCH \
      --uri "https://graph.microsoft.com/v1.0/applications/$APP_OBJECT_ID" \
      --headers "Content-Type=application/json" \
      --body "{\"spa\":{\"redirectUris\":[\"$LOCALHOST_REDIRECT\"]}}" \
      --output none 2>/dev/null || true

    echo "  Configured SPA redirect URI: $LOCALHOST_REDIRECT"
  fi
fi
echo "  Entra Client ID: $ENTRA_CLIENT_ID"

# ---------- 3b. Configure API scope ------------------------------------------
echo ""
echo ">>> Configuring API scope..."

APP_OBJECT_ID=$(az ad app show --id "$ENTRA_CLIENT_ID" --query "id" -o tsv)

# Set Application ID URI if not already set
IDENTIFIER_URIS=$(az ad app show --id "$ENTRA_CLIENT_ID" --query "identifierUris[0]" -o tsv 2>/dev/null || true)
if [[ -z "$IDENTIFIER_URIS" || "$IDENTIFIER_URIS" == "None" ]]; then
  az ad app update --id "$ENTRA_CLIENT_ID" --identifier-uris "api://$ENTRA_CLIENT_ID"
  echo "  Set Application ID URI: api://$ENTRA_CLIENT_ID"
else
  echo "  Application ID URI already set: $IDENTIFIER_URIS"
fi

# Add access_as_user scope if not present
HAS_SCOPE=$(az ad app show --id "$ENTRA_CLIENT_ID" \
  --query "api.oauth2PermissionScopes[?value=='access_as_user'].value" -o tsv 2>/dev/null || true)
if [[ -z "$HAS_SCOPE" ]]; then
  SCOPE_ID=$(python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null \
    || powershell.exe -Command "[guid]::NewGuid().ToString()" 2>/dev/null \
    || cat /proc/sys/kernel/random/uuid 2>/dev/null \
    || uuidgen)
  az rest --method PATCH \
    --uri "https://graph.microsoft.com/v1.0/applications/$APP_OBJECT_ID" \
    --headers "Content-Type=application/json" \
    --body "{\"api\":{\"oauth2PermissionScopes\":[{\"adminConsentDescription\":\"Access SimpleConnect as the signed-in user\",\"adminConsentDisplayName\":\"Access SimpleConnect\",\"id\":\"$SCOPE_ID\",\"isEnabled\":true,\"type\":\"User\",\"userConsentDescription\":\"Access SimpleConnect on your behalf\",\"userConsentDisplayName\":\"Access SimpleConnect\",\"value\":\"access_as_user\"}]}}" \
    --output none
  echo "  Added scope: api://$ENTRA_CLIENT_ID/access_as_user"
else
  echo "  Scope access_as_user already configured"
fi

# ---------- 4. Create resource group -----------------------------------------
echo ""
echo ">>> Creating resource group (if it does not exist)..."
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none
echo "  Resource group ready: $RESOURCE_GROUP ($LOCATION)"

# ---------- 5. Deploy ARM template -------------------------------------------
echo ""
echo ">>> Deploying ARM template..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$TEMPLATE_FILE" \
  --parameters "@${PARAMETERS_FILE}" \
  --parameters \
    projectName="$PROJECT_NAME" \
    entraTenantId="consumers" \
    entraClientId="$ENTRA_CLIENT_ID" \
    adminObjectIds="$ADMIN_OBJECT_ID" \
  --output json)

FUNCTION_APP_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.functionAppName.value')
FUNCTION_APP_URL=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.functionAppUrl.value')
KEY_VAULT_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.properties.outputs.keyVaultName.value')

echo "  Function App : $FUNCTION_APP_NAME"
echo "  Function URL : $FUNCTION_APP_URL"
echo "  Key Vault    : $KEY_VAULT_NAME"

# ---------- 6. Persist settings -----------------------------------------------
echo ""
echo ">>> Persisting settings..."
save_env

# ---------- 7. Update Entra app redirect URIs ---------------------------------
echo ""
echo ">>> Updating Entra app redirect URIs..."

DEPLOYED_REDIRECT="${FUNCTION_APP_URL}/authentication/login-callback"
APP_OBJECT_ID=$(az ad app show --id "$ENTRA_CLIENT_ID" --query "id" -o tsv)

az rest --method PATCH \
  --uri "https://graph.microsoft.com/v1.0/applications/$APP_OBJECT_ID" \
  --headers "Content-Type=application/json" \
  --body "{\"spa\":{\"redirectUris\":[\"$LOCALHOST_REDIRECT\",\"$DEPLOYED_REDIRECT\"]}}" \
  --output none

echo "  Redirect URIs: $LOCALHOST_REDIRECT, $DEPLOYED_REDIRECT"

# ---------- 8. Build and deploy code ------------------------------------------
if [[ "$INFRA_ONLY" == "true" ]]; then
  echo ""
  echo "============================================================"
  echo " Infrastructure deployment complete!"
  echo "============================================================"
  echo " Environment    : $ENVIRONMENT"
  echo " Function App   : $FUNCTION_APP_URL"
  echo " Entra Client ID: $ENTRA_CLIENT_ID"
  echo " Key Vault      : $KEY_VAULT_NAME"
  echo " Settings saved : $ENV_FILE"
  echo ""
  echo " Run without --infra-only to also build and deploy code:"
  echo "   ./build.sh --env $ENVIRONMENT"
  echo "   ./deploy.sh --env $ENVIRONMENT"
  echo "============================================================"
  exit 0
fi

echo ""
echo ">>> Building and deploying code..."
"$SCRIPT_DIR/build.sh" --env "$ENVIRONMENT"
"$SCRIPT_DIR/deploy.sh" --env "$ENVIRONMENT"

# ---------- done ---------------------------------------------------------------
echo ""
echo "============================================================"
echo " Setup complete!"
echo "============================================================"
echo " Environment    : $ENVIRONMENT"
echo " Function App   : $FUNCTION_APP_URL"
echo " Entra Client ID: $ENTRA_CLIENT_ID"
echo " Admin Object ID: $ADMIN_OBJECT_ID"
echo " Key Vault      : $KEY_VAULT_NAME"
echo " Settings saved : $ENV_FILE"
echo ""
echo " Next steps:"
echo "   1. Open $FUNCTION_APP_URL in your browser"
echo "   2. Sign in with your Microsoft account"
echo "   3. Create a room and share the invite link"
echo ""
echo " For subsequent deploys:"
echo "   ./deploy.sh --env $ENVIRONMENT"
echo "============================================================"
