#Requires -Version 7.0
<#
.SYNOPSIS
    Full setup and deployment for SimpleConnect.

.DESCRIPTION
    Handles everything from scratch: Entra app registration, resource group,
    ARM deployment, build, deploy, and redirect URI configuration.
    Persists all settings to .env.{environment} for future runs.

.PARAMETER Environment
    Deployment environment: staging or prod. Prompted if not provided.

.PARAMETER InfraOnly
    Deploy only the ARM template (no code build/deploy).

.EXAMPLE
    ./setup.ps1
    ./setup.ps1 -Environment staging
    ./setup.ps1 -Environment staging -InfraOnly
#>

[CmdletBinding()]
param(
    [ValidateSet("staging", "prod")]
    [string]$Environment,

    [string]$ResourceGroup,
    [string]$Location,
    [string]$ProjectName,

    [switch]$InfraOnly
)

$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
$projectRoot = Split-Path $scriptDir -Parent
$appName = "SimpleConnect"

# ---------- load persisted settings ------------------------------------------
function Load-EnvFile([string]$envFile) {
    $settings = @{}
    if (Test-Path $envFile) {
        Write-Host ">>> Loading persisted settings from $envFile"
        Get-Content $envFile | ForEach-Object {
            if ($_ -match '^\s*([A-Z_]+)\s*=\s*"(.*)"\s*$') {
                $settings[$Matches[1]] = $Matches[2]
            }
        }
    }
    return $settings
}

function Save-EnvFile([string]$envFile, [hashtable]$values) {
    $lines = @(
        "# SimpleConnect persisted settings"
        "# Auto-generated by setup.ps1 - do not commit to source control"
    )
    foreach ($key in ($values.Keys | Sort-Object)) {
        $lines += "$key=`"$($values[$key])`""
    }
    Set-Content -Path $envFile -Value ($lines -join "`n") -Encoding UTF8
    Write-Host "  Saved to $envFile"
}

function Invoke-GraphPatch([string]$appObjectId, [hashtable]$body) {
    $bodyFile = [System.IO.Path]::GetTempFileName()
    try {
        $body | ConvertTo-Json -Depth 5 | Set-Content -Path $bodyFile -Encoding UTF8
        az rest --method PATCH `
            --uri "https://graph.microsoft.com/v1.0/applications/$appObjectId" `
            --headers "Content-Type=application/json" `
            --body "@$bodyFile" --output none 2>$null
    }
    finally {
        Remove-Item $bodyFile -Force -ErrorAction SilentlyContinue
    }
}

# ---------- interactive prompts for missing values ---------------------------
if ([string]::IsNullOrWhiteSpace($Environment)) {
    $Environment = Read-Host "Environment (staging/prod)"
    if ($Environment -notin @("staging", "prod")) {
        throw "Environment must be 'staging' or 'prod'"
    }
}

$envFile = Join-Path $scriptDir ".env.$Environment"
$persisted = Load-EnvFile $envFile

if ([string]::IsNullOrWhiteSpace($ResourceGroup)) {
    $default = if ($persisted["RESOURCE_GROUP"]) { $persisted["RESOURCE_GROUP"] } else { "rg-simcon-$Environment" }
    $input = Read-Host "Resource group name [$default]"
    $ResourceGroup = if ([string]::IsNullOrWhiteSpace($input)) { $default } else { $input }
}

if ([string]::IsNullOrWhiteSpace($Location)) {
    $default = if ($persisted["LOCATION"]) { $persisted["LOCATION"] } else { "southeastasia" }
    Write-Host ""
    Write-Host "  Available regions (common):"
    Write-Host "    southeastasia  - Singapore"
    Write-Host "    eastasia       - Hong Kong"
    Write-Host "    japaneast      - Tokyo"
    Write-Host "    koreacentral   - Seoul"
    Write-Host "    northeurope    - Ireland"
    Write-Host "    westeurope     - Netherlands"
    Write-Host ""
    $input = Read-Host "Azure region [$default]"
    $Location = if ([string]::IsNullOrWhiteSpace($input)) { $default } else { $input }
}

if ([string]::IsNullOrWhiteSpace($ProjectName)) {
    if ($persisted["PROJECT_NAME"]) {
        $default = $persisted["PROJECT_NAME"]
    } else {
        # First run — generate a random suffix so Azure names don't collide
        $randomSuffix = -join ((0x30..0x39) + (0x61..0x66) | Get-Random -Count 4 | ForEach-Object { [char]$_ })
        $default = "simcon-$randomSuffix"
    }
    Write-Host ""
    Write-Host "  Project name is used for Azure resource naming (must be globally unique)."
    $input = Read-Host "Project name prefix [$default]"
    $ProjectName = if ([string]::IsNullOrWhiteSpace($input)) { $default } else { $input }
}

$templateFile = Join-Path $scriptDir "azuredeploy.json"
$parametersFile = Join-Path $scriptDir "parameters.$Environment.json"

if (-not (Test-Path $templateFile)) { throw "ARM template not found at $templateFile" }
if (-not (Test-Path $parametersFile)) { throw "Parameter file not found at $parametersFile" }

$entraClientId = $persisted["ENTRA_CLIENT_ID"]
$adminObjectId = $persisted["ADMIN_OBJECT_IDS"]

Write-Host ""
Write-Host "============================================================"
Write-Host " SimpleConnect - Setup ($Environment)$(if ($InfraOnly) { ' [Infra Only]' })"
Write-Host "============================================================"
Write-Host " Resource Group : $ResourceGroup"
Write-Host " Location       : $Location"
Write-Host " Project Name   : $ProjectName"
Write-Host "============================================================"

# ---------- 1. Check Azure CLI login ----------------------------------------
Write-Host ""
Write-Host ">>> Checking Azure CLI login..."
try {
    $account = az account show --output json 2>$null | ConvertFrom-Json
    Write-Host "  Subscription: $($account.name) ($($account.id))"
}
catch {
    throw "Not logged in to Azure CLI. Run 'az login' first."
}

# ---------- 2. Get signed-in user's Object ID -------------------------------
if ([string]::IsNullOrWhiteSpace($adminObjectId)) {
    Write-Host ""
    Write-Host ">>> Getting your user Object ID..."
    $adminObjectId = az ad signed-in-user show --query "id" -o tsv 2>$null

    if ([string]::IsNullOrWhiteSpace($adminObjectId)) {
        Write-Host "  Could not auto-detect Object ID (personal accounts may not support this)."
        $adminObjectId = Read-Host "  Enter your Entra Object ID manually"
        if ([string]::IsNullOrWhiteSpace($adminObjectId)) {
            throw "Admin Object ID is required."
        }
    }
}
else {
    Write-Host ""
    Write-Host ">>> Using persisted Admin Object ID: $adminObjectId"
}
Write-Host "  Admin Object ID: $adminObjectId"

# ---------- 3. Register or update Entra ID app ------------------------------
Write-Host ""
Write-Host ">>> Registering Entra ID application..."

$entraAppDisplayName = "$appName-$Environment"
$localhostRedirect = "http://localhost:7071/authentication/login-callback"

if (-not [string]::IsNullOrWhiteSpace($entraClientId)) {
    Write-Host "  Using persisted app registration: $entraClientId"
}
else {
    $existingAppId = az ad app list `
        --display-name $entraAppDisplayName `
        --query "[0].appId" -o tsv 2>$null

    if (-not [string]::IsNullOrWhiteSpace($existingAppId) -and $existingAppId -ne "None") {
        Write-Host "  App registration found: $existingAppId"
        $entraClientId = $existingAppId
    }
    else {
        Write-Host "  Creating new app registration: $entraAppDisplayName"

        $entraClientId = az ad app create `
            --display-name $entraAppDisplayName `
            --sign-in-audience "AzureADandPersonalMicrosoftAccount" `
            --enable-id-token-issuance true `
            --web-redirect-uris $localhostRedirect `
            --query "appId" -o tsv

        Write-Host "  Created app: $entraClientId"

        $appObjectId = az ad app show --id $entraClientId --query "id" -o tsv
        Invoke-GraphPatch $appObjectId @{ spa = @{ redirectUris = @($localhostRedirect) } }
        Write-Host "  Configured SPA redirect URI: $localhostRedirect"
    }
}
Write-Host "  Entra Client ID: $entraClientId"

# ---------- 3b. Configure API scope ------------------------------------------
Write-Host ""
Write-Host ">>> Configuring API scope..."

$appObjectId = az ad app show --id $entraClientId --query "id" -o tsv

# Set Application ID URI if not already set
$identifierUri = az ad app show --id $entraClientId --query "identifierUris[0]" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($identifierUri) -or $identifierUri -eq "None") {
    az ad app update --id $entraClientId --identifier-uris "api://$entraClientId"
    Write-Host "  Set Application ID URI: api://$entraClientId"
} else {
    Write-Host "  Application ID URI already set: $identifierUri"
}

# Add access_as_user scope if not present
$hasScope = az ad app show --id $entraClientId `
    --query "api.oauth2PermissionScopes[?value=='access_as_user'].value" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($hasScope)) {
    $scopeId = [guid]::NewGuid().ToString()
    Invoke-GraphPatch $appObjectId @{
        api = @{
            oauth2PermissionScopes = @(
                @{
                    adminConsentDescription = "Access SimpleConnect as the signed-in user"
                    adminConsentDisplayName  = "Access SimpleConnect"
                    id                      = $scopeId
                    isEnabled               = $true
                    type                    = "User"
                    userConsentDescription  = "Access SimpleConnect on your behalf"
                    userConsentDisplayName  = "Access SimpleConnect"
                    value                   = "access_as_user"
                }
            )
        }
    }
    Write-Host "  Added scope: api://$entraClientId/access_as_user"
} else {
    Write-Host "  Scope access_as_user already configured"
}

# ---------- 4. Create resource group -----------------------------------------
Write-Host ""
Write-Host ">>> Creating resource group (if it does not exist)..."
az group create --name $ResourceGroup --location $Location --output none
Write-Host "  Resource group ready: $ResourceGroup ($Location)"

# ---------- 5. Deploy ARM template -------------------------------------------
Write-Host ""
Write-Host ">>> Deploying ARM template..."
$deploymentOutput = az deployment group create `
    --resource-group $ResourceGroup `
    --template-file $templateFile `
    --parameters "@$parametersFile" `
    --parameters `
        projectName=$ProjectName `
        entraTenantId="consumers" `
        entraClientId=$entraClientId `
        adminObjectIds=$adminObjectId `
    --output json | ConvertFrom-Json

$functionAppName = $deploymentOutput.properties.outputs.functionAppName.value
$functionAppUrl = $deploymentOutput.properties.outputs.functionAppUrl.value
$keyVaultName = $deploymentOutput.properties.outputs.keyVaultName.value

Write-Host "  Function App : $functionAppName"
Write-Host "  Function URL : $functionAppUrl"
Write-Host "  Key Vault    : $keyVaultName"

# ---------- 6. Persist settings -----------------------------------------------
Write-Host ""
Write-Host ">>> Persisting settings..."
Save-EnvFile $envFile @{
    ENTRA_CLIENT_ID  = $entraClientId
    ADMIN_OBJECT_IDS = $adminObjectId
    RESOURCE_GROUP   = $ResourceGroup
    LOCATION         = $Location
    PROJECT_NAME     = $ProjectName
    FUNCTION_APP_NAME = $functionAppName
    FUNCTION_APP_URL = $functionAppUrl
    KEY_VAULT_NAME   = $keyVaultName
}

# ---------- 7. Update Entra app redirect URIs ---------------------------------
Write-Host ""
Write-Host ">>> Updating Entra app redirect URIs..."

$deployedRedirect = "$functionAppUrl/authentication/login-callback"
$appObjectId = az ad app show --id $entraClientId --query "id" -o tsv

Invoke-GraphPatch $appObjectId @{
    spa = @{ redirectUris = @($localhostRedirect, $deployedRedirect) }
}

Write-Host "  Redirect URIs: $localhostRedirect, $deployedRedirect"

# ---------- 8. Build and deploy code ------------------------------------------
if ($InfraOnly) {
    Write-Host ""
    Write-Host "============================================================"
    Write-Host " Infrastructure deployment complete!"
    Write-Host "============================================================"
    Write-Host " Environment    : $Environment"
    Write-Host " Function App   : $functionAppUrl"
    Write-Host " Entra Client ID: $entraClientId"
    Write-Host " Key Vault      : $keyVaultName"
    Write-Host " Settings saved : $envFile"
    Write-Host ""
    Write-Host " Run without -InfraOnly to also build and deploy code:"
    Write-Host "   ./build.ps1 -Environment $Environment"
    Write-Host "   ./deploy.ps1 -Environment $Environment"
    Write-Host "============================================================"
    exit 0
}

Write-Host ""
Write-Host ">>> Building and deploying code..."
& "$scriptDir/build.ps1" -Environment $Environment
& "$scriptDir/deploy.ps1" -Environment $Environment

# ---------- done ---------------------------------------------------------------
Write-Host ""
Write-Host "============================================================"
Write-Host " Setup complete!"
Write-Host "============================================================"
Write-Host " Environment    : $Environment"
Write-Host " Function App   : $functionAppUrl"
Write-Host " Entra Client ID: $entraClientId"
Write-Host " Admin Object ID: $adminObjectId"
Write-Host " Key Vault      : $keyVaultName"
Write-Host " Settings saved : $envFile"
Write-Host ""
Write-Host " Next steps:"
Write-Host "   1. Open $functionAppUrl in your browser"
Write-Host "   2. Sign in with your Microsoft account"
Write-Host "   3. Create a room and share the invite link"
Write-Host ""
Write-Host " For subsequent deploys:"
Write-Host "   ./deploy.ps1 -Environment $Environment"
Write-Host "============================================================"
